### ISSUE TITLE
shim-rune questions

### ISSUE THREAD

**Issue by mythi** [alibaba/inclavare-containers#576]
Hi,

I've been reading the documentation and I have a few questions I've not been able to find the answers.

1.  shim-rune/Carrier framework/Signature framework: Is inclavare shim able to convert *any* container application into an Occlum libOS based application using the Carrier and Signature frameworks? what is `signature_method=server|client`?
2. where to find detailed information about what the shim does when the container is created? in particular, I'd like to understand how EPM is used and how the cached enclave is re-used for multiple containers from different tenants running on the kubernetes node. who signs the original enclave? is the original enclave derived from 'skeleton'?
3. What is `liberpal`?

Thanks!

**Comment by jiazhang0** [comment]
1. Theoretically it is true. In practice, it is decided by the binary compatibility provided by LibOS. For example, gsgx is able to run native binaries, so the converted container application can be launched successfully with a high probability. The early versions of Occlum only support musl-c, so the container application must be developed with musl-c ([Occlum 0.19.0](https://github.com/occlum/occlum/releases/tag/0.19.0) now supports glibc). `signature_method=server|client` equals to on-cloud signing and off-clouding signing correspondingly.
2. If we don't talk about EPM, shim-rune does nothing special than shim-runc in off-cloud signing mode, and shim will use carrier and signature frameworks to convert container application in on-cloud signing. With EPM framework, shim-rune can leverage the bundle cache to speed up the launch of enclave runtime from scratch without converting container application again. This function is not documented in [EPM design doc](https://github.com/alibaba/inclavare-containers/blob/master/docs/design/epm/design.md), because it is still experimental for on-cloud signing scheme. Enclave cache is another function of EPM, and doesn't care the scheme of signing. So it is good to distinguish signing scheme from EPM functions. For different tenants, the pools managed by EPM should be isolated. @YangLiang3 @jiazhiguang Please feel free to discuss this topic :)
3. `liberpal` is the common name for [PAL](https://github.com/alibaba/inclavare-containers/issues/576). It is the abbreviation of 'the library of enclave runtime PAL'.

**Comment by mythi** [comment]
@jiazhang0 thanks for the quick replies, much appreciated!

The documentation (for the newcomers like me) is not very clear on the two different use-cases (on-cloud signing and off-cloud signing). Perhaps add the definitions for these to the main README that describes them?

> shim-rune does nothing special than shim-runc in off-cloud signing mode,

is the attestation handled directly between the container (init-runelet) and `inclavared`?

**Comment by jiazhang0** [comment]
> @jiazhang0 thanks for the quick replies, much appreciated!
> 
> The documentation (for the newcomers like me) is not very clear on the two different use-cases (on-cloud signing and off-cloud signing). Perhaps add the definitions for these to the main README that describes them?

Sure. We will clarify them.

> 
> > shim-rune does nothing special than shim-runc in off-cloud signing mode,
> 
> is the attestation handled directly between the container (init-runelet) and `inclavared`?

Yes it is.

**Comment by jiazhang0** [comment]
@mythi I just close this issue. If you need any help, please re-open it.
