### ISSUE TITLE
RA-TLS implementation with Occlum runtime

### ISSUE THREAD

**Issue by srieyulianti** [alibaba/inclavare-containers#745]
Hi Inclavare Containers team,

I have looked through your RA-TLS project. The project is really helpful as a reference for my thesis. Thanks for providing the example. I am wondering whether the project can be implemented by using another runtime such as Occlum Library OS? As I can see right now, your implementation is using SGX-SDK based runtime.

Best Regards,
Sri Yulianti

**Comment by jiazhang0** [comment]
@srieyulianti Actually the credit of ra-tls should be given to https://github.com/cloud-security-research/sgx-ra-tls, where we originally refer to. Essentially ra-tls in inclavare containers just port the wolfssl sgx-sdk part with epic and ecdsa based attestation logic, and then we extend it with LA support.

Currently, we are working with Occlum to run [enclave-tis (early code)](https://github.com/alibaba/inclavare-containers/tree/enclave-tls) rather than ra-tls.

ra-tls has many limits against what we expect to. For example, it binds to a modified wolfssl, introducing extra maintenance effort. In addition, it cannot support heterogeneous confidential compute platform attestation, e.g, a SEV VM attested by a SGX enclave. This is what enclave-tls will resolve. All codes of enclave-tis will be published soon, and the Occulm part will be contributed to Occlum community.

**Comment by srieyulianti** [comment]
Hi @jiazhang0 ,

Thanks for your good explanation. So what I can understand from your current implementation is the remote attestation based on TLS implementation is left to wolfssl SGX-SDK and you extend the LA support to run the workloads in enclave runtime which can use Occlum as an example. 
Thanks for your suggestion about enclave-tls. I will be waiting for the code to release :)

Best Regards,
Sri Yulianti

**Comment by hustliyilin** [comment]
> Hi @jiazhang0 ,
> 
> Thanks for your good explanation. So what I can understand from your current implementation is the remote attestation based on TLS implementation is left to wolfssl SGX-SDK and you extend the LA support to run the workloads in enclave runtime which can use Occlum as an example.
> Thanks for your suggestion about enclave-tls. I will be waiting for the code to release :)
> 
> Best Regards,
> Sri Yulianti

`ra-tls` isn't a part of this repo any more, Please refer to [this guide](https://github.com/alibaba/inclavare-containers/tree/master/enclave-tls#occlum-libos) to run enclave-tls with occlum @srieyulianti .

**Comment by jiazhang0** [comment]
@srieyulianti I just close this issue. If you need any help, please re-open it.
