### ISSUE TITLE
enclave-tls: clean up enclave-tls-client/server

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#747]
- drop sub-command parsing logic.

**Comment by haosanzi** [comment]
enclave-tls-client/server has been reconstructed in c language. The reason is that we want to integrate enclave-tls with Occlum, however, `occlum-go` can not compile `enclave-tls-client/server` which is written in `golang`.  The `go_flags` cannot be correctly recognized by `occlum-go` unless we change the `occlum-go` script.
